'use client';

import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { FileText, BookOpen, AlertCircle } from 'lucide-react';

const sections = [
  {
    id: 'overview',
    title: '1. Overview',
    content: `This Content Use & Copyright Policy ("Policy") governs the creation, upload, distribution, and use of educational content on the SRP Education AI platform ("Platform") operated by SRP AI Labs.

We respect intellectual property rights and expect all users to do the same. This Policy explains your rights and responsibilities regarding content on the Platform.`,
  },
  {
    id: 'ai-generated',
    title: '2. AI-Generated Educational Content',
    content: `Our Platform generates educational content using artificial intelligence. Important disclosures:

• AI-generated content (study notes, explanations, quizzes, summaries, current affairs Q&A) is created as original educational assistance
• The Platform generates fresh explanations and does NOT reproduce copyrighted textbooks verbatim
• AI-generated content may occasionally contain inaccuracies and should be cross-verified
• Content generated by the AI is provided for personal and institutional educational use
• You may use AI-generated study materials for your own learning, classroom teaching, and student assessment
• AI-generated content should not be republished commercially without permission`,
  },
  {
    id: 'user-content',
    title: '3. User-Uploaded Content',
    content: `When uploading content to the Platform:

Rights & Permissions:
• You must own or have explicit permission to upload all content
• You are responsible for ensuring your uploaded materials do not infringe any third-party copyrights, trademarks, or other intellectual property rights
• Institutions uploading content must ensure they have appropriate licenses for any educational materials distributed through the Platform

Prohibited Content:
• Verbatim reproduction of copyrighted textbooks, reference books, or published test papers
• Scanned copies of commercially published educational materials without publisher permission
• Pirated software, tools, or digital learning resources
• Content from other platforms redistributed without proper licensing

Permitted Content:
• Original study notes, summaries, and explanations created by the uploader
• Teacher-created assessments, worksheets, and educational resources
• Content licensed under Creative Commons or similar open licenses (with proper attribution)
• Institutional materials created for internal use
• Student-created projects, notes, and study materials`,
  },
  {
    id: 'current-affairs',
    title: '4. Current Affairs & Dynamic Content',
    content: `Our current affairs and general knowledge features:

• Generate original summaries and Q&A based on publicly available information
• Do NOT reproduce copyrighted news articles verbatim
• Content is AI-synthesized from general knowledge and may not reflect the very latest events
• All dynamically generated content includes clear date markers for freshness verification
• Users should cross-reference with authoritative news sources for accuracy
• The Platform does not guarantee real-time accuracy of current affairs content`,
  },
  {
    id: 'dmca',
    title: '5. Copyright Complaints & DMCA',
    content: `If you believe that content on our Platform infringes your copyright, please submit a complaint to:

Email: legal@srpailabs.com
Subject: "Copyright Infringement Report"

Your complaint should include:
• A description of the copyrighted work you claim has been infringed
• The specific URL or location of the allegedly infringing content on our Platform
• Your contact information (name, email, phone)
• A statement that you have a good faith belief that the use is not authorized
• A statement, under penalty of perjury, that the information in the complaint is accurate and that you are authorized to act on behalf of the copyright owner
• Your physical or electronic signature

We will investigate all complaints and respond within 10 business days. If infringement is confirmed, the content will be promptly removed.`,
  },
  {
    id: 'institution',
    title: '6. Institution Content Responsibilities',
    content: `Institutions using the Platform agree to:

• Ensure all uploaded educational materials are properly licensed or originally created
• Take responsibility for content shared within their tenant/instance
• Designate a content administrator responsible for content compliance
• Respond promptly to any copyright complaints related to their institutional content
• Not use the Platform to distribute proprietary content of competing institutions
• Maintain appropriate records of content licensing and permissions`,
  },
  {
    id: 'licensing',
    title: '7. Platform Content Licensing',
    content: `• Platform IP: The Platform's interface, design, codebase, and original educational tools are the intellectual property of SRP AI Labs
• User Content: You retain ownership of original content you upload. By uploading, you grant SRP AI Labs a non-exclusive license to host, display, and distribute the content within the Platform for educational purposes
• AI Output: AI-generated content is provided for your educational use under a non-exclusive license. You may use it for personal study, classroom teaching, and institutional academic purposes
• Attribution: If you share or publish Platform-generated content externally, appropriate attribution to "SRP Education AI" is appreciated but not legally required for educational use`,
  },
  {
    id: 'updates',
    title: '8. Policy Updates',
    content: `This Policy may be updated periodically. We will notify users of significant changes via email or platform notification. Continued use after changes constitutes acceptance.

Last updated: April 2026`,
  },
];

export default function ContentPolicyPage() {
  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <div className="w-16 h-16 bg-amber-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <BookOpen className="w-8 h-8 text-amber-600" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Content Use & Copyright Policy</h1>
            <p className="text-gray-500">Last updated: April 2026</p>
          </div>

          {/* Key Notice */}
          <div className="mb-8 p-4 bg-amber-50 border border-amber-200 rounded-2xl flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-amber-800">
              <strong>Important:</strong> SRP Education AI generates original educational explanations and does NOT reproduce copyrighted textbooks verbatim. All AI-generated content is meant to supplement learning, not replace official educational materials.
            </div>
          </div>

          <div className="space-y-8">
            {sections.map((section) => (
              <div key={section.id} id={section.id} className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm">
                <h2 className="text-lg font-semibold text-gray-900 mb-3">{section.title}</h2>
                <div className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">{section.content}</div>
              </div>
            ))}
          </div>

          <div className="mt-12 text-center">
            <p className="text-sm text-gray-500">
              For copyright inquiries, contact{' '}
              <a href="mailto:legal@srpailabs.com" className="text-brand-600 hover:text-brand-700 font-medium">legal@srpailabs.com</a>
            </p>
            <div className="flex items-center justify-center gap-4 mt-4 text-sm">
              <Link href="/terms" className="text-brand-600 hover:text-brand-700">Terms of Service</Link>
              <span className="text-gray-300">|</span>
              <Link href="/privacy" className="text-brand-600 hover:text-brand-700">Privacy Policy</Link>
              <span className="text-gray-300">|</span>
              <Link href="/acceptable-use" className="text-brand-600 hover:text-brand-700">Acceptable Use</Link>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
