// ──────────────────────────────────────────────────────────────
// Citation Manager — Manages source attribution & content policy
// ──────────────────────────────────────────────────────────────

/**
 * Trusted sources that can be referenced for facts extraction.
 * The AI reads from these for signals and facts, NOT for direct copying.
 */
export const TRUSTED_SOURCES = {
  government: [
    'PIB (Press Information Bureau)',
    'RBI (Reserve Bank of India)',
    'SEBI (Securities and Exchange Board of India)',
    'PRS India (PRS Legislative Research)',
    'Ministry websites (GOI)',
    'Election Commission of India',
    'NITI Aayog',
    'Finance Ministry',
    'Ministry of Health and Family Welfare',
  ],
  international: [
    'WHO (World Health Organization)',
    'UN (United Nations)',
    'IMF (International Monetary Fund)',
    'World Bank',
    'WTO (World Trade Organization)',
    'UNESCO',
    'UNICEF',
    'CDC (Centers for Disease Control)',
    'NHS (National Health Service)',
  ],
  medical: [
    'NMC (National Medical Commission)',
    'Indian Nursing Council',
    'Indian Pharmacopoeia Commission',
    'ICMR (Indian Council of Medical Research)',
    'PubMed / NCBI',
    'WHO Clinical Guidelines',
    'Harrison\'s Principles of Internal Medicine',
    'Guyton & Hall Textbook of Medical Physiology',
    'Bailey & Love Surgery',
    'KD Tripathi Pharmacology',
  ],
  education: [
    'NCERT',
    'UGC',
    'CBSE',
    'State Board syllabi',
    'AICTE',
    'NTA (National Testing Agency)',
  ],
  engineering: [
    'NPTEL (IIT/IISc)',
    'GATE previous year papers',
    'IS Codes (Bureau of Indian Standards)',
    'ASME Standards',
    'IEEE Standards',
    'Standard textbooks (Cormen, PK Nag, Khurmi, Sedra & Smith, Cengel)',
  ],
  commerce: [
    'ICAI (Institute of Chartered Accountants of India)',
    'ICSI (Institute of Company Secretaries of India)',
    'ICMAI (Institute of Cost Accountants of India)',
    'Companies Act 2013',
    'Income Tax Act 1961',
    'GST Act 2017',
    'Ind AS / Indian Accounting Standards',
    'SEBI Regulations',
    'RBI Circulars',
    'TS Grewal, DK Goel, Tulsian textbooks',
  ],
  industry: [
    'BIS (Bureau of Indian Standards)',
    'ISO Standards',
    'OSHA guidelines',
    'DGMS (Directorate General of Mines Safety)',
    'FSSAI',
    'MCA (Ministry of Corporate Affairs)',
  ],
} as const;

/**
 * Blocked copy sources — NEVER reproduce text from these.
 */
export const BLOCKED_COPY_SOURCES = [
  'Indian Express',
  'Hindustan Times',
  'Deccan Chronicle',
  'The Hindu',
  'Times of India',
  'NDTV',
  'India Today',
  'Livemint',
  'Economic Times',
  'Business Standard',
  'Reuters',
  'AP News',
  'BBC',
  'CNN',
  'The Guardian',
  'New York Times',
  'Washington Post',
] as const;

/**
 * Builds the content policy prompt section for AI system prompts.
 */
export function buildContentPolicyPrompt(domain?: string): string {
  const trustedList = domain === 'medical'
    ? [...TRUSTED_SOURCES.government, ...TRUSTED_SOURCES.medical]
    : domain === 'engineering' || domain === 'industry'
    ? [...TRUSTED_SOURCES.government, ...TRUSTED_SOURCES.industry, ...TRUSTED_SOURCES.engineering]
    : domain === 'commerce' || domain === 'finance'
    ? [...TRUSTED_SOURCES.government, ...TRUSTED_SOURCES.commerce]
    : [...TRUSTED_SOURCES.government, ...TRUSTED_SOURCES.international, ...TRUSTED_SOURCES.education];

  return `
CONTENT POLICY — STRICTLY ENFORCED:
1. Do NOT copy or republish paragraphs from any newspaper or copyrighted publication.
2. Do NOT include wire service attributions (PTI, ANI, IANS, Reuters, AP).
3. Read multiple trusted sources, extract facts, dates, official statements, and trends.
4. Cross-check information across sources before including.
5. Generate ORIGINAL SRP Education AI educational summaries in your own words.
6. Use sources for signals and facts, NOT for direct text copying.

TRUSTED REFERENCE SOURCES:
${trustedList.map(s => `- ${s}`).join('\n')}

Every generated output must be:
- Original in wording
- Structured for learners
- Factually accurate
- Properly attributed when citing specific data points`;
}

/**
 * Adds source attribution to content when specific data is referenced.
 */
export function buildSourceAttribution(sources: string[]): string {
  if (sources.length === 0) return '';
  return `\n\n---\n**Sources Referenced:** ${sources.join(', ')}\n*Content is original educational summary generated by SRP Education AI. Not copied from any publication.*`;
}
