import Link from 'next/link';
import { Sparkles, ArrowLeft, FileText, Shield, Scale, AlertCircle } from 'lucide-react';

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using SRP Education AI ("Platform"), operated by SRP AI Labs ("Company", "we", "us", "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Platform.

These Terms apply to all visitors, users, students, teachers, institution administrators, and any other person who accesses or uses the Platform.`,
  },
  {
    id: 'accounts',
    title: '2. User Accounts & Registration',
    content: `To access most features, you must create an account. When registering, you agree to:

• Provide accurate, current, and complete information during the registration process
• Maintain and promptly update your registration information to keep it accurate
• Maintain the security of your password and accept all risks of unauthorized access
• Notify us immediately if you discover any unauthorized use of your account
• Not create accounts for others without their explicit consent
• Not share your login credentials with any third party

Accounts for B2B institutional users are managed by the institution's designated administrator. Individual user accounts within an institution are subject to both these Terms and any additional terms set by the institution.`,
  },
  {
    id: 'acceptable-use',
    title: '3. Acceptable Use Policy',
    content: `You agree to use the Platform only for lawful educational purposes. You must NOT:

• Upload, share, or distribute content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable
• Attempt to gain unauthorized access to any portion of the Platform, other accounts, or systems connected to the Platform
• Use the Platform for any commercial purpose other than as expressly permitted
• Use automated scripts, bots, or scraping tools to access the Platform
• Interfere with or disrupt the Platform or servers connected to the Platform
• Impersonate any person or entity or falsely state your affiliation with a person or entity
• Share exam content or proprietary materials in violation of copyright laws
• Attempt to reverse-engineer, decompile, or disassemble any part of the Platform

Violation of these terms may result in immediate suspension or termination of your account without notice.`,
  },
  {
    id: 'intellectual-property',
    title: '4. Intellectual Property Rights',
    content: `The Platform and its original content (excluding content provided by users), features, and functionality are and shall remain the exclusive property of SRP AI Labs and its licensors.

• User-Generated Content: Content you create, upload, or submit to the Platform remains your property. By submitting content, you grant us a non-exclusive, worldwide, royalty-free license to use, display, and distribute such content solely for the purpose of operating and improving the Platform.
• AI-Generated Content: Content generated by our AI tools is provided for your personal educational use. You may use AI-generated study materials, notes, and quizzes for your own learning purposes.
• Platform IP: Our trademarks, logos, service marks, and trade names may not be used without prior written consent.`,
  },
  {
    id: 'subscriptions',
    title: '5. Subscriptions & Payments',
    content: `• Free Tier: Basic features are available at no cost with limited functionality.
• Paid Plans: Paid subscriptions (Student Pro, Career Premium, Institution plans) are billed monthly or annually as selected.
• Payment Processing: Payments in India are processed via Razorpay. International payments are processed via Stripe. All transactions are subject to applicable taxes including 18% GST for Indian users.
• Auto-Renewal: Paid subscriptions renew automatically unless cancelled before the renewal date.
• Cancellation: You may cancel your subscription at any time. Access continues until the end of the current billing period.
• Refunds: We offer a 7-day money-back guarantee for first-time subscribers of paid plans. After 7 days, refunds are at our sole discretion.
• Price Changes: We reserve the right to modify pricing with 30 days prior notice. Existing subscriptions continue at the original price until renewal.`,
  },
  {
    id: 'ai-services',
    title: '6. AI Services & Limitations',
    content: `Our Platform uses artificial intelligence to provide educational assistance. Please note:

• AI-generated responses are meant to supplement, not replace, professional educational instruction
• While we strive for accuracy, AI responses may occasionally contain errors or inaccuracies
• AI features are provided "as is" and should not be relied upon as the sole source of information for critical academic decisions
• We continuously improve our AI models but do not guarantee specific outcomes or results
• Usage limits may apply to AI features based on your subscription plan`,
  },
  {
    id: 'institution-terms',
    title: '7. Institution-Specific Terms',
    content: `For institutions (schools, colleges, coaching centers, universities) using our multi-tenant platform:

• Data Ownership: Student and institutional data belongs to the institution. We process this data as a service provider.
• White-Label: Institutions may customize branding as permitted by their subscription plan.
• Administrator Responsibility: Institution administrators are responsible for managing user accounts, permissions, and compliance with applicable education regulations.
• Data Export: Institutions may request a complete export of their data at any time.
• Termination: Upon termination, institutional data will be available for export for 30 days, after which it will be securely deleted.`,
  },
  {
    id: 'termination',
    title: '8. Termination',
    content: `We may terminate or suspend your account immediately, without prior notice, for any reason including, without limitation, breach of these Terms. Upon termination:

• Your right to use the Platform ceases immediately
• We may delete your account and associated data after a 30-day grace period
• Provisions that by their nature should survive termination shall survive (including intellectual property, limitation of liability, and dispute resolution provisions)

You may delete your account at any time through your account settings or by contacting support.`,
  },
  {
    id: 'liability',
    title: '9. Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

• The Platform is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, whether express or implied
• SRP AI Labs shall not be liable for any indirect, incidental, special, consequential, or punitive damages
• Our total liability for any claim arising out of or relating to these Terms shall not exceed the amount you paid us in the 12 months preceding the event giving rise to the claim
• We do not guarantee uninterrupted, timely, secure, or error-free operation of the Platform`,
  },
  {
    id: 'governing-law',
    title: '10. Governing Law & Disputes',
    content: `These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these Terms or the use of the Platform shall be subject to the exclusive jurisdiction of the courts in India.

We encourage users to contact us directly at support@srpailabs.com to resolve any issues before pursuing formal dispute resolution.`,
  },
  {
    id: 'modifications',
    title: '11. Modifications to Terms',
    content: `We reserve the right to modify these Terms at any time. Material changes will be communicated through:

• Email notification to your registered email address
• A prominent notice on the Platform
• Updated "Last Modified" date on this page

Your continued use of the Platform after the effective date of revised Terms constitutes acceptance of the changes.`,
  },
  {
    id: 'contact',
    title: '12. Contact Information',
    content: `For questions about these Terms of Service, please contact us:

• Email: support@srpailabs.com
• Website: srpailabs.com
• Response Time: Within 2 business days`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-gray-100/50">
        <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-9 h-9 bg-gradient-to-br from-brand-600 to-violet-600 rounded-xl flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-gray-900">SRP Education AI</span>
          </Link>
          <Link href="/" className="btn-secondary text-sm inline-flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative pt-32 pb-12 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-brand-50/40 via-white to-white" />
        <div className="relative max-w-3xl mx-auto px-6 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-brand-100/80 text-brand-700 rounded-full text-sm font-semibold mb-6 border border-brand-200/50">
            <Scale className="w-4 h-4" />
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-gray-500 text-sm">
            Last updated: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>
      </section>

      {/* Quick Nav */}
      <section className="max-w-3xl mx-auto px-6 mb-12">
        <div className="card-elevated">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-brand-600" />
            <h2 className="text-sm font-bold text-gray-900">Table of Contents</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {sections.map((s) => (
              <a key={s.id} href={`#${s.id}`} className="text-sm text-brand-600 hover:text-brand-700 hover:underline transition-colors">
                {s.title}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 pb-24">
        <div className="space-y-10">
          {sections.map((s) => (
            <section key={s.id} id={s.id} className="scroll-mt-24">
              <h2 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-100">{s.title}</h2>
              <div className="text-sm text-gray-600 leading-relaxed whitespace-pre-line">{s.content}</div>
            </section>
          ))}
        </div>

        {/* Notice */}
        <div className="mt-16 p-6 bg-amber-50 rounded-2xl border border-amber-100">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-semibold text-amber-900">Important Notice</p>
              <p className="text-sm text-amber-700 mt-1">
                This document constitutes a legally binding agreement. If you have questions about any of these terms,
                please contact us at <a href="mailto:support@srpailabs.com" className="font-medium underline">support@srpailabs.com</a> before using the Platform.
              </p>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-8">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-sm">&copy; {new Date().getFullYear()} SRP AI Labs. All rights reserved.</p>
          <div className="flex items-center gap-6 text-sm">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms of Service</Link>
            <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
