export enum Role {
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  TEACHER = 'TEACHER',
  DEPARTMENT_ADMIN = 'DEPARTMENT_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  INSTITUTION_OWNER = 'INSTITUTION_OWNER',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum AccountType {
  B2C_STUDENT = 'B2C_STUDENT',
  B2B_INSTITUTION = 'B2B_INSTITUTION',
}

export enum TokenType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  B2C_SIGNUP = 'B2C_SIGNUP',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  USER_APPROVED = 'USER_APPROVED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  CONTENT_CREATED = 'CONTENT_CREATED',
  CONTENT_APPROVED = 'CONTENT_APPROVED',
  CONTENT_REJECTED = 'CONTENT_REJECTED',
  CONTENT_FLAGGED = 'CONTENT_FLAGGED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_UPGRADED = 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_DOWNGRADED = 'SUBSCRIPTION_DOWNGRADED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  COUPON_APPLIED = 'COUPON_APPLIED',
  BRANDING_UPDATED = 'BRANDING_UPDATED',
  ADDON_ACTIVATED = 'ADDON_ACTIVATED',
  ADDON_DEACTIVATED = 'ADDON_DEACTIVATED',
  REFERRAL_CREATED = 'REFERRAL_CREATED',
  REFERRAL_CONVERTED = 'REFERRAL_CONVERTED',
  AI_CHAT_CREATED = 'AI_CHAT_CREATED',
  ACCOUNT_LINKED_TO_INSTITUTION = 'ACCOUNT_LINKED_TO_INSTITUTION',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
}

export enum NotificationType {
  SYSTEM = 'SYSTEM',
  NEW_REGISTRATION = 'NEW_REGISTRATION',
  SECURITY_ALERT = 'SECURITY_ALERT',
  ERROR_ALERT = 'ERROR_ALERT',
  PAYMENT = 'PAYMENT',
  CONTENT = 'CONTENT',
  SUBSCRIPTION = 'SUBSCRIPTION',
}

export const ADMIN_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.INSTITUTION_OWNER,
  Role.INSTITUTION_ADMIN,
  Role.DEPARTMENT_ADMIN,
];

export const TENANT_ADMIN_ROLES: Role[] = [
  Role.INSTITUTION_OWNER,
  Role.INSTITUTION_ADMIN,
];

export const MAX_LOGIN_ATTEMPTS = 5;
export const LOCK_DURATION_MINUTES = 30;
export const EMAIL_TOKEN_EXPIRY_HOURS = 24;
export const PASSWORD_RESET_EXPIRY_HOURS = 1;
